-- MySQL Script generated by MySQL Workbench
-- Thu May  1 11:31:58 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sistema_escolar
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `sistema_escolar` ;

-- -----------------------------------------------------
-- Schema sistema_escolar
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sistema_escolar` DEFAULT CHARACTER SET utf8 ;
USE `sistema_escolar` ;

-- -----------------------------------------------------
-- Table `sistema_escolar`.`actividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`actividades` (
  `id_actividad` INT NOT NULL AUTO_INCREMENT,
  `nombre_actividad` VARCHAR(150) CHARACTER SET 'utf8' NOT NULL,
  `descripcion` TEXT CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `fecha_creacion` DATE NOT NULL,
  PRIMARY KEY (`id_actividad`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`nivel` (
  `id_nivel` INT NOT NULL AUTO_INCREMENT,
  `tipo_nivel` ENUM('super', 'normal') CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`estados` (
  `id_estado` INT NOT NULL AUTO_INCREMENT,
  `estados` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `iso-3166-2` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_estado`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`ciudades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`ciudades` (
  `id_ciudad` INT NOT NULL AUTO_INCREMENT,
  `id_estado` INT NOT NULL,
  `ciudades` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_ciudad`),
  CONSTRAINT `id_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `sistema_escolar`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_estado_idx` ON `sistema_escolar`.`ciudades` (`id_estado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`municipios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`municipios` (
  `id_municipios` INT NOT NULL AUTO_INCREMENT,
  `id_estado` INT NOT NULL,
  `municipios` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_municipios`),
  CONSTRAINT `id_estado`
    FOREIGN KEY (`id_estado`)
    REFERENCES `sistema_escolar`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_estado_idx` ON `sistema_escolar`.`municipios` (`id_estado` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`parroquias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`parroquias` (
  `id_parroquia` INT NOT NULL AUTO_INCREMENT,
  `id_municipio` INT NOT NULL,
  `parroquia` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_parroquia`),
  CONSTRAINT `id_municipio`
    FOREIGN KEY (`id_municipio`)
    REFERENCES `sistema_escolar`.`municipios` (`id_municipios`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_municipio_idx` ON `sistema_escolar`.`parroquias` (`id_municipio` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`direccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`direccion` (
  `id_direccion` INT NOT NULL AUTO_INCREMENT,
  `direccion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `id_ciudad` INT NOT NULL,
  `id_parroquia` INT NOT NULL,
  PRIMARY KEY (`id_direccion`),
  CONSTRAINT `id_ciudad`
    FOREIGN KEY (`id_ciudad`)
    REFERENCES `sistema_escolar`.`ciudades` (`id_ciudad`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_parroquia`
    FOREIGN KEY (`id_parroquia`)
    REFERENCES `sistema_escolar`.`parroquias` (`id_parroquia`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `id_parroquia_idx` ON `sistema_escolar`.`direccion` (`id_parroquia` ASC) VISIBLE;

CREATE INDEX `id_ciudad_idx` ON `sistema_escolar`.`direccion` (`id_ciudad` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`usuarios` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `id_nivel` INT NOT NULL,
  `id_direccion` INT NOT NULL,
  `primer_nombre` VARCHAR(85) CHARACTER SET 'utf8' NOT NULL,
  `segundo_nombre` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `apellido` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `segundo_apellido` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `correo` VARCHAR(60) CHARACTER SET 'utf8' NOT NULL,
  `contraseña` VARCHAR(34) NOT NULL,
  `rol` ENUM('admin', 'estudiante') NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT '1',
  `ultima_conexion` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_usuario`),
  CONSTRAINT `id_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `sistema_escolar`.`nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_direccion`
    FOREIGN KEY (`id_direccion`)
    REFERENCES `sistema_escolar`.`direccion` (`id_direccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE UNIQUE INDEX `correo` ON `sistema_escolar`.`usuarios` (`correo` ASC) VISIBLE;

CREATE INDEX `id_nivel_idx` ON `sistema_escolar`.`usuarios` (`id_nivel` ASC) VISIBLE;

CREATE INDEX `id_direccion_idx` ON `sistema_escolar`.`usuarios` (`id_direccion` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`usuario_administradores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`usuario_administradores` (
  `id_admin` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `id_nivel` INT NOT NULL,
  `contraseña` VARCHAR(34) NOT NULL,
  PRIMARY KEY (`id_admin`),
  CONSTRAINT `id_nivel`
    FOREIGN KEY (`id_nivel`)
    REFERENCES `sistema_escolar`.`nivel` (`id_nivel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_usuario`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_escolar`.`usuarios` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_nivel_idx` ON `sistema_escolar`.`usuario_administradores` (`id_nivel` ASC) VISIBLE;

CREATE INDEX `id_usuario_idx` ON `sistema_escolar`.`usuario_administradores` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`bitacora`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`bitacora` (
  `id_accion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `accion_realizada` TEXT CHARACTER SET 'utf8' NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id_accion`),
  CONSTRAINT `bitacora_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_escolar`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_usuario` ON `sistema_escolar`.`bitacora` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`comentarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`comentarios` (
  `id_comentario` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `mensaje` TEXT CHARACTER SET 'utf8' NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  PRIMARY KEY (`id_comentario`),
  CONSTRAINT `comentarios_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_escolar`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_usuario` ON `sistema_escolar`.`comentarios` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`estudiantes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`estudiantes` (
  `id_estudiante` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_estudiante`),
  CONSTRAINT `estudiantes_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_escolar`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_usuario` ON `sistema_escolar`.`estudiantes` (`id_usuario` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`materias` (
  `id_materia` INT NOT NULL AUTO_INCREMENT,
  `nombre_materia` VARCHAR(100) CHARACTER SET 'utf8' NOT NULL,
  `descripcion` TEXT CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_materia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`seccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`seccion` (
  `id_seccion` INT NOT NULL AUTO_INCREMENT,
  `seccion` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`id_seccion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`periodo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`periodo` (
  `id_periodo` INT NOT NULL AUTO_INCREMENT,
  `periodo` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `fechaInicio` DATE NOT NULL,
  `fechaFinal` DATE NOT NULL,
  PRIMARY KEY (`id_periodo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`matricula`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`matricula` (
  `id_matricula` INT NOT NULL AUTO_INCREMENT,
  `id_estudiante` INT NOT NULL,
  `id_periodo` INT NOT NULL,
  `id_seccion` INT NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT '1',
  PRIMARY KEY (`id_matricula`),
  CONSTRAINT `matricula_ibfk_1`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `sistema_escolar`.`estudiantes` (`id_estudiante`),
  CONSTRAINT `id_seccion`
    FOREIGN KEY (`id_seccion`)
    REFERENCES `sistema_escolar`.`seccion` (`id_seccion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_periodo`
    FOREIGN KEY (`id_periodo`)
    REFERENCES `sistema_escolar`.`periodo` (`id_periodo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_estudiante` ON `sistema_escolar`.`matricula` (`id_estudiante` ASC) VISIBLE;

CREATE INDEX `id_seccion_idx` ON `sistema_escolar`.`matricula` (`id_seccion` ASC) VISIBLE;

CREATE INDEX `id_periodo_idx` ON `sistema_escolar`.`matricula` (`id_periodo` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`matricula_materias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`matricula_materias` (
  `id_matricula` INT NOT NULL,
  `id_materia` INT NOT NULL,
  PRIMARY KEY (`id_matricula`, `id_materia`),
  CONSTRAINT `matricula_materias_ibfk_1`
    FOREIGN KEY (`id_matricula`)
    REFERENCES `sistema_escolar`.`matricula` (`id_matricula`),
  CONSTRAINT `matricula_materias_ibfk_2`
    FOREIGN KEY (`id_materia`)
    REFERENCES `sistema_escolar`.`materias` (`id_materia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_materia` ON `sistema_escolar`.`matricula_materias` (`id_materia` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`notas` (
  `id_nota` INT NOT NULL AUTO_INCREMENT,
  `id_actividad` INT NOT NULL,
  `id_estudiante` INT NOT NULL,
  `nota_obtenida` DECIMAL(5,2) NOT NULL,
  PRIMARY KEY (`id_nota`),
  CONSTRAINT `notas_ibfk_1`
    FOREIGN KEY (`id_actividad`)
    REFERENCES `sistema_escolar`.`actividades` (`id_actividad`),
  CONSTRAINT `notas_ibfk_2`
    FOREIGN KEY (`id_estudiante`)
    REFERENCES `sistema_escolar`.`estudiantes` (`id_estudiante`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_actividad` ON `sistema_escolar`.`notas` (`id_actividad` ASC) VISIBLE;

CREATE INDEX `id_estudiante` ON `sistema_escolar`.`notas` (`id_estudiante` ASC) VISIBLE;


-- -----------------------------------------------------
-- Table `sistema_escolar`.`notificaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sistema_escolar`.`notificaciones` (
  `id_notificacion` INT NOT NULL AUTO_INCREMENT,
  `id_usuario` INT NOT NULL,
  `mensaje` TEXT CHARACTER SET 'utf8' NOT NULL,
  `fecha_hora` DATETIME NOT NULL,
  `estado` TINYINT(1) NULL DEFAULT '0',
  PRIMARY KEY (`id_notificacion`),
  CONSTRAINT `notificaciones_ibfk_1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `sistema_escolar`.`usuarios` (`id_usuario`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

CREATE INDEX `id_usuario` ON `sistema_escolar`.`notificaciones` (`id_usuario` ASC) VISIBLE;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
